### ISSUE TITLE
Set-D365Admin does not work when entering optional Params

### ISSUE THREAD

**Issue by Wolfram66** [d365collaborative/d365fo.tools#272]
Set-D365Admin -AdminSignInName MKO@contoso.com -DatabaseServer localhost -DatabaseName AxDB -verbose

Exception calling "Invoke" with "2" argument(s): "Parameter count mismatch."
At line:3565 char:5
+     $UpdateAdminUser.Invoke($null, $params)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : TargetParameterCountException

function **Set-D365Admin** 
    
        return
    **### Set-AdminUser** $AdminSignInName $DatabaseServer $DatabaseName $SqlUser $SqlPwd

Function Name and User name do not match... is that normal?

**Comment by Splaxi** [comment]
Hi, 

Thanks for posting your issue.

If you are running on a Tier1 box, either a local VHD / onebox or a Cloud hosted Tier1, you shouldn't have to run the command with other parameters than -AdminSignInName. The other parameters have default values configured, so you shouldn't worry about those.

```
Set-D365Admin -AdminSignInName MKO@contoso.com -Verbose
```

We have seen some issues where the batch service was not able to either stop fully or couldn't be started afterwards. We are actually using some internal components from Microsoft, so we can't really say what goes wrong.

Could you share your environment details? Are you able to stop alle services using the module? Please check that the batch service actually stays in the stopped state even after 1 minute. Microsoft put in the service configuration that the batch service should recover from failures and will keep doing. A solution it **NOT** to disable the batch service. This will prevent you from running the cmdlet / function correctly.

Did you try to use the real provision tool from Microsoft? When ever we have faced this issue, the provision tool wasn't able to work either.

Try rebooting the machine and make sure that you are able to stop and start the services, including validating that the batch stays stopped when you run the Stop-D365Environment.

**Comment by Wolfram66** [comment]
Thank you for the prompt reply.

This is a VM in our Columbus Cloud environment… Yes it is a OneBox installation for Development, with a twist:

What we have created is a multi-client instance environment with what amounts to a Hot-Swap ability to switch the D365FO instance from customer to customer.

Clicking on the Company1.bat will set the D365FO environment to look at the Company1 segmented objects.  AxDBCompany1, AOSService\PackagesLocalDirectoryCompany1…

In the effort to save money, this is to allow the user or users to swap between customers rather than spin up additional VM’s.

Still working the kinks out. And yes we have tried the standard AdminProvisioning Tool. This does not seem to work either with the latest update to this environment.

We will check the Batch service. [I did run into it not being able to stop yesterday]


Warm regards,

Mark A. Kopan
Consultant / EDI FSA
[cid:image001.png@01D50B05.91F14D70]<https://www.columbusglobal.com/en/solutions/erp-crm-solutions/microsoft-dynamics-365/>
Office: 425-654-1156
Mobile: 440 622-3313
E-mail: MKO@columbusglobal.com<mailto:MKO@columbusglobal.com>

[image003]<https://twitter.com/us_columbus>  [image004] <https://www.linkedin.com/company/columbus-a-s>   [image006] <https://www.youtube.com/user/uscolumbuserp>

**Comment by Splaxi** [comment]
Interesting scenario that you are trying to achieve!

A small recommendation for you. Make it work for CustomerA on a single box, like designed by Microsoft. When it works, backup the database and bring it into your multi environment. Then you shouldn't need to provision when switching between your Customers configs.

From what I have learned until now, is that if you know all the details, you can just change the values in dbo.UserInfo table for the id = 'admin' record, restart all the D365FO services (or the machine entirely) and it will work. Try that and reach out if you need a hand, wanna learn more about how you do what you are doing, simply because it seems like a fun exercise 😆

**Comment by Splaxi** [comment]
Hi,

Just wanted to check on the issue.

We'll close the issue 10th of June, if no further development has been made.

**Comment by devax** [comment]
I want to jump on to this issue, as we encounter the same error after having upgraded our VMs from PU 24 to PU26. It appears to me, that with the version PU 26, Microsoft has introduced a second (mandatory?) parameter to the AdminUserProvisioning, see screenshot:
![image](https://user-images.githubusercontent.com/22288651/59141318-fcc93080-89aa-11e9-83ba-2e27a3249487.png)

On environments with PU 26 installed, this command: 
`Set-D365Admin -AdminSignInName test@test.com`
results in this error:
```
Exception calling "Invoke" with "2" argument(s): "Parameter count mismatch."
At line:3566 char:5
+     $UpdateAdminUser.Invoke($null, $params)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : TargetParameterCountException
```

**Comment by Splaxi** [comment]
Great work!

I'll give it a look over the weekend and see if I can find a solution to it 👍

**Comment by Splaxi** [comment]
I believe I found the missing pieces.

For now we will not support AAD-China.

0.5.39 should fix the issue and should be available in 30 minutes...

**Comment by devax** [comment]
Thank you @Splaxi for looking into this! 
I have just given it a try but unfortunately it still fails. Here is the command I use together with its verbose output:
```
PS C:\windows\system32> Set-D365Admin test@test.com
VERBOSE: [08:19:43][Set-AdminUser] MetaDataDirectory: C:\AOSService\PackagesLocalDirectory
VERBOSE: [08:19:43][Set-AdminUser] Testing for PU26 or higher
VERBOSE: [08:19:43][Set-AdminUser] PU26 or higher found. Will adjust parameters.
VERBOSE: [08:19:43][Set-AdminUser] Updating Admin using the values test@test.com, localhost, AxDB, axdbadmin, AOSWebSite@123
Exception calling "Invoke" with "2" argument(s): "Object reference not set to an instance of an object."
At line:3574 char:5
+     $UpdateAdminUser.Invoke($null, $params)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException
```

```
PS C:\windows\system32> Get-InstalledModule d365fo.tools

Version              Name                                Repository           Description                                                                                                                             
-------              ----                                ----------           -----------                                                                                                                             
0.5.39               d365fo.tools                        PSGallery            A set of tools that will assist you when working with Dynamics 365 Finance & Operations development / demo machines.                    
```

**Comment by Splaxi** [comment]
Thx for testing so quickly.

I'll give it some more attention...

**Comment by Splaxi** [comment]
@devax 

Update is that I think I found the issue and will release new version tomorrow night...

**Comment by Splaxi** [comment]
Hi @devax 

0.5.40 contains the latest take on solving the issue.

Please test and let me know how things look...

**Comment by devax** [comment]
Hi @Splaxi ,
Sorry for the late reply, I was on holidays! ;-)
I can confirm the error is gone on a PU 26 environment. I cannot test on other environments, because that is the only one I have currently available.
Thank you very much for sorting this out for us, it is highly appreciated!

**Comment by devax** [comment]
Hi @Splaxi 
I have a local dev box that I have just updated to PU29/Appl. 10.0.5 PREVIEW version. So maybe I'm a bit too early to report this, but I let you know anyways. The `Set-D365Admin` command seems to be broken on these machines, again. Here is the verbose output of the command, together with some additional version infos:

```
PS C:\windows\system32> Get-InstalledModule -Name d365fo.tools

Version              Name                                Repository           Description                                                                 
-------              ----                                ----------           -----------                                                                 
0.5.41               d365fo.tools                        PSGallery            A set of tools that will assist you when working with Dynamics 365 Financ...



PS C:\windows\system32> Get-D365ProductInformation


ProductVersion          : 7.0
ProductBuildVersion     : 7.0.5372.16646
ProductBuildBranch      : rainfndstab
PlatformVersion         : Update29
PlatformBuildVersion    : 7.0.5372.16646
PlatformBranch          : rainfndstab
ApplicationVersion      : 10.0.5
ApplicationBuildVersion : 10.0.197.16
ApplicationBranch       : appmustab
ProductRegisteredName   : Microsoft Dynamics 365 for Finance and Operations




PS C:\windows\system32> Set-D365Admin -AdminSignInName test@test.com
VERBOSE: [16:51:30][Set-AdminUser] MetaDataDirectory: C:\AOSService\PackagesLocalDirectory
You cannot call a method on a null-valued expression.
At line:3635 char:5
+     $UpdateAdminUser = $AdminUserUpdater.GetMethod("UpdateAdminUser", ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
VERBOSE: [16:51:30][Set-AdminUser] Testing for PU26 or higher
You cannot call a method on a null-valued expression.
At line:3638 char:8
+     if((($UpdateAdminUser.GetParameters()).Name) -contains "providerN ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
VERBOSE: [16:51:30][Set-AdminUser] Updating Admin using the values test@test.com, localhost, AxDB, axdbadmin, AOSWebSite@123
[16:51:30][Set-AdminUser] Something went wrong while provisioning the environment to the new administrator: test@test.com. | You cannot call a method on a null-valued expression.
WARNING: [16:51:30][Set-AdminUser] Stopping because of errors. | Something went wrong while provisioning the environment to the new administrator: test@tes
t.com.

PS C:\windows\system32>
```

**Comment by Splaxi** [comment]
Never to early, that is what testing is for!

I'll find a command for you to run, so we can test things, because I don't have access to PU29 at the moment.

**Comment by Splaxi** [comment]
Are things still breaking for you?

**Comment by devax** [comment]
Yes, but I'm still on 10.0.5 preview version. I planned to update to the 10.0.6 preview anyway, so I can re-check with the newer version.

**Comment by devax** [comment]
Hey @Splaxi , guess it's ok to use my real name here: Mark Furrer, my (not really used) twitter handle is @devax_mf. You can add this info, if you like to. I'm glad I could contribute something!

**Comment by Splaxi** [comment]
Hey @devax 

Please download the latest release  0.5.45 and double check that things work like expected.

I'll close this issue down, let us create a new one if we need to visit the Set-D365Admin again.

**Comment by devax** [comment]
Just downloaded the newest and it seems to work like a charm. Excellent!

**Comment by Splaxi** [comment]
All thanks to you! 💪🤘
