### ISSUE TITLE
Invoke-D365SDPInstall $topologyFile is an empty string

### ISSUE THREAD

**Issue by FH-Inway** [d365collaborative/d365fo.tools#324]
When running `Invoke-D365SDPInstall -Path "c:\temp\update" -RunbookId "cu-20191011" -Command RunAll` with the 10.0.6 update, I get the following error:
```
Test-PathExists : Cannot bind argument to parameter 'Path' because it is an empty string.
At line:16041 char:37
+     if (-not (Test-PathExists -Path $topologyFile, $Util -Type Leaf)) ...
+                                     ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-PathExists], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Test-PathExists
```
`get-module d365fo.tools` lists version 0.5.49.

**Comment by FH-Inway** [comment]
Note that despite the error, AXUpdateInstaller.exe is still being called, but doesn't seem to do anything.

**Comment by Splaxi** [comment]
If you didn't close the powershell session, you can run:
Get-PSFMessage -Level Verbose

Otherwise could you please try and run the command with the -Verbose and share the output?

**Comment by FH-Inway** [comment]
Here's the verbose output 

```
PS C:\windows\system32> cd C:\temp\Update

PS C:\temp\Update> Import-Module d365fo.tools -Force 

PS C:\temp\Update> Invoke-D365SDPInstall -Path "c:\temp\update" -RunbookId "cu-20191011" -Command RunAll -verbose
VERBOSE: [14:14:26][Test-AssembliesLoaded] Total time spent inside the function was 00:00:00.0156752
VERBOSE: [14:14:26][Test-PathExists] Testing the path: C:\Logs\InstallationRecords\Runbooks
VERBOSE: [14:14:26][Test-PathExists] Testing the path: C:\Logs\InstallationRecords\Runbooks\Runbook_20191001102821edaaf5cb-db1f-4dbd-85b5-4cf560102318.xml
VERBOSE: [14:14:27][Test-PathExists] Testing the path: C:\Logs\InstallationRecords\Runbooks\Runbook_201909301345070b92eafc-e416-46ea-806a-03a3c6b0a7d3.xml
VERBOSE: [14:14:27][Test-PathExists] Testing the path: C:\Logs\InstallationRecords\Runbooks\Runbook_20190710174032d38bc44b-e36f-4e34-8be8-f4595a668511.xml
VERBOSE: [14:14:27][Test-PathExists] Testing the path: C:\Logs\InstallationRecords\Runbooks\Runbook_201906261750170116ea36-fa1c-4a68-96bb-9904c56db4b4.xml
VERBOSE: [14:14:27][Test-PathExists] Testing the path: C:\Logs\InstallationRecords\Runbooks\Runbook_201906111020236f9df4c4-077a-4b69-8de0-3335c4a9b647.xml
VERBOSE: [14:14:27][Test-PathExists] Testing the path: C:\Logs\InstallationRecords\Runbooks\Runbook_20190523164351ad2bb18a-87bf-4fe2-a2c5-f3b094cff809.xml
VERBOSE: [14:14:28][Test-PathExists] Testing the path: C:\Logs\InstallationRecords\Runbooks\Runbook_201904251018304aa445bb-e26c-48e8-9c77-32411f88dcd1.xml
VERBOSE: [14:14:28][Test-PathExists] Testing the path: C:\Logs\InstallationRecords\Runbooks\Runbook_20190425095949849e395f-df2e-4f8e-b865-aa1897632e21.xml
VERBOSE: [14:14:28][Test-PathExists] Testing the path: C:\Logs\InstallationRecords\Runbooks\Runbook_20190417150706b2d080db-0f22-4350-8eba-93a1f0beb48e.xml
VERBOSE: [14:14:28][Test-PathExists] Testing the path: C:\Logs\InstallationRecords\Runbooks\Runbook_20190412162031bc0dc8ec-4af7-40d5-be65-18e638f37928.xml
VERBOSE: [14:14:29][Test-PathExists] Testing the path: C:\Logs\InstallationRecords\Runbooks\Runbook_201904111751332f976327-92c0-436d-83a7-64b4e5bf4404.xml
VERBOSE: [14:14:29][Test-PathExists] Testing the path: C:\Logs\InstallationRecords\Runbooks\Runbook_2019040409444426be459e-1789-4345-9de1-6c533d5577dc.xml
VERBOSE: [14:14:29][Test-PathExists] Testing the path: C:\Logs\InstallationRecords\Runbooks\Runbook_20190315150538d9c667e7-2be0-4285-bd5a-dc57c7d7989d.xml
Test-PathExists : Cannot bind argument to parameter 'Path' because it is an empty string.
At line:16041 char:37
+     if (-not (Test-PathExists -Path $topologyFile, $Util -Type Leaf)) ...
+                                     ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-PathExists], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Test-PathExists
 
VERBOSE: [14:14:35][Invoke-D365SDPInstall] Running all manual steps in one single operation
VERBOSE: [14:14:35][Update-TopologyFile] Creating topology file: c:\temp\update\DefaultTopologyData.xml
VERBOSE: [14:14:35][Test-PathExists] Testing the path: c:\temp\update\Microsoft.Dynamics.AX.AXInstallationInfo.dll
VERBOSE: [14:14:35][Import-AssemblyFileIntoMemory] Cloning c:\temp\update\Microsoft.Dynamics.AX.AXInstallationInfo.dll to c:\temp\update\Microsoft.Dynamics.AX.AXInstallationInfo.dll_shadow.dl
l
VERBOSE: [14:14:35][Import-AssemblyFileIntoMemory] Loading c:\temp\update\Microsoft.Dynamics.AX.AXInstallationInfo.dll_shadow.dll into memory
VERBOSE: [14:14:35][Import-AssemblyFileIntoMemory] Removing c:\temp\update\Microsoft.Dynamics.AX.AXInstallationInfo.dll_shadow.dll
VERBOSE: [14:14:35][Import-AssemblyFileIntoMemory] Total time spent inside the function was 00:00:00.0781262
VERBOSE: [14:14:35][Test-PathExists] Testing the path: c:\temp\update\AXUpdateInstaller.exe
VERBOSE: [14:14:35][Invoke-Process] Output and Error streams will be redirected (silence mode)
VERBOSE: [14:14:35][Invoke-Process] Starting the AXUpdateInstaller.exe
VERBOSE: [14:14:35][Invoke-Process] Waiting for the AXUpdateInstaller.exe to complete
VERBOSE: [14:14:36][Invoke-Process] Standard output was: \r\n 
VERBOSE: [14:14:36][Invoke-Process] Total time spent inside the function was 00:00:00.7343669
VERBOSE: [14:14:36][Test-PathExists] Testing the path: c:\temp\update\AXUpdateInstaller.exe
VERBOSE: [14:14:36][Invoke-Process] Output and Error streams will be redirected (silence mode)
VERBOSE: [14:14:36][Invoke-Process] Starting the AXUpdateInstaller.exe
VERBOSE: [14:14:36][Invoke-Process] Waiting for the AXUpdateInstaller.exe to complete
VERBOSE: [14:14:36][Invoke-Process] Standard output was: \r\n 
VERBOSE: [14:14:36][Invoke-Process] Total time spent inside the function was 00:00:00.6250408
VERBOSE: [14:14:36][Test-PathExists] Testing the path: c:\temp\update\AXUpdateInstaller.exe
VERBOSE: [14:14:36][Invoke-Process] Output and Error streams will be redirected (silence mode)
VERBOSE: [14:14:36][Invoke-Process] Starting the AXUpdateInstaller.exe
```

**Comment by Splaxi** [comment]
I believe I have found the bug.

Give me 10-20 minutes to confirm and test my findings. I it is a bug, I'll make a quick release with it, so you can continue with your work!

**Comment by FH-Inway** [comment]
Thanks, but no need to rush this. I executed the update manually (which felt like going back to the stone age :)). But I kept a checkpoint of my VM right before the update. Happy to check your fix when you are done.

**Comment by Splaxi** [comment]
Haha! Thanks for putting a smile on my face. I'm going to use "Stone Age" in one of my presentations for the next conference, where I will be talking about my tools.

The build is running, when it completes, I'll merge and the the auto publish will kick in. I expect less than 30 minutes from now.

**Comment by Splaxi** [comment]
Fixed in: 0.5.50 

Which has been released right now!

**Comment by FH-Inway** [comment]
Unfortunately, the issue persists with the new version. Verbose output is the same as before.

**Comment by FH-Inway** [comment]
After looking at the [commit](https://github.com/d365collaborative/d365fo.tools/commit/e662866dba24da7950c7a96ffce74f6758d2ffdb): Shouldn't the error message have at least change to the following (`$executable` instead of `$Util`)? But I'm definitely on version 0.5.50. Is Powershell doing some kind of caching of modules? I will try a restart of the VM.

```
Test-PathExists : Cannot bind argument to parameter 'Path' because it is an empty string.
At line:16041 char:37
+     if (-not (Test-PathExists -Path $topologyFile, $executable -Type Leaf)) ...
+                                     ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-PathExists], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Test-PathExists
```

**Comment by FH-Inway** [comment]
Ok, now it works. I think what went wrong was that I updated the tools, but then didn't do an `Import-Module` again. So the tools were updated, but the imported version was still the old one.

**Comment by Splaxi** [comment]
I still forget to import the latest version from time to time 🙊🙉🙈

**Comment by FH-Inway** [comment]
Yeah, also `-ShowOriginalProgress $true` is helpful, was a bit stumped at first because nothing seemed to be happening.

**Comment by Splaxi** [comment]
It is actually on purpose we suppress the output. When running in an automated pipeline it can quickly blow up / bloat the console and make it hard to troubleshoot later.

But when we are debugging and testing, the ShowOriginalProgress is very helpful. Other cmdlets also have the ShowOriginalProgress if you look closer 😉
