### ISSUE TITLE
Cannot find type [Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob]: verify that the assembly containing this type is loaded

### ISSUE THREAD

**Issue by oathgg** [d365collaborative/d365fo.tools#447]
I have obfuscated some of the information for privacy reasons.
While trying to upload a new asset through the "Invoke-D365LcsUpload" command, I receive an error:

**Command used:**
```
Get-D365LcsApiToken `
-ClientId "xxxxxx" `
-Username "xxxxxxx" `
-Password "xxxxxx" `
-LcsApiUri "https://lcsapi.lcs.dynamics.com" `
| Set-D365LcsApiConfig

Invoke-D365LcsUpload `
-ProjectId xxxx `
-FilePath "C:\Temp\AXDeployableRuntime_2020.7.8.1.zip" `
-FileType "Software Deployable Package" `
-FileName "FLEX_TEST_AUTOMATED_UPLOAD" `
-LcsApiUri "https://lcsapi.lcs.dynamics.com"
```

**Error:**
```
VERBOSE: [13:32:19][Start-LcsUpload] Json payload for LCS generated.
VERBOSE: [13:32:19][New-JsonRequest] Building a HttpRequestMessage.
VERBOSE: [13:32:19][New-JsonRequest] Adding content to the HttpRequestMessage.
VERBOSE: [13:32:19][New-JsonRequest] Adding Authorization token to the HttpRequestMessage.
VERBOSE: [13:32:19][Start-LcsUpload] Invoke LCS request.
VERBOSE: [13:32:19][Get-AsyncResult] Building the Task Waiter and start waiting.
VERBOSE: [13:32:21][Start-LcsUpload] Extracting the response received from LCS.
VERBOSE: [13:32:21][Get-AsyncResult] Building the Task Waiter and start waiting.
VERBOSE: [13:32:21][Start-LcsUpload] Extracting the response received from LCS.
VERBOSE: [13:32:21][Start-LcsUpload] Extracting the asset json response received from LCS.
VERBOSE: [13:32:21][Start-LcsUpload] Total time spent inside the function was 00:00:01.9860949
VERBOSE: [13:32:21][Invoke-D365LcsUpload] Start response
VERBOSE: [13:32:21][Invoke-TimeSignal] The command 'Copy-FileToLcsBlob' was already taking part in time measurement. The entry has been update with current date and time.
VERBOSE: [13:32:21][Copy-FileToLcsBlob] Initializing the needed .net objects to work against Azure Blob.
New-Object : Cannot find type [Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob]: verify that the assembly containing this type is loaded.
At line:42 char:18
+ ... cloudblob = New-Object -TypeName Microsoft.WindowsAzure.Storage.Blob. ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
 
[13:32:21][Copy-FileToLcsBlob] Something went wrong while uploading the desired file to Azure Blob. | You cannot call a method on a null-valued expression.
WARNING: [13:32:21][Copy-FileToLcsBlob] Stopping because of errors
VERBOSE: [13:32:21][Invoke-D365LcsUpload] Upload response
VERBOSE: [13:32:21][New-JsonRequest] Building a HttpRequestMessage.
VERBOSE: [13:32:21][New-JsonRequest] Adding Authorization token to the HttpRequestMessage.
VERBOSE: [13:32:21][Complete-LcsUpload] Sending the commit request against LCS
VERBOSE: [13:32:21][Get-AsyncResult] Building the Task Waiter and start waiting.
VERBOSE: [13:32:22][Complete-LcsUpload] Parsing the commitResult for success
VERBOSE: [13:32:22][Complete-LcsUpload] Total time spent inside the function was 00:00:01.2102954
VERBOSE: [13:32:22][Invoke-D365LcsUpload] Commit response
VERBOSE: [13:32:22][Invoke-D365LcsUpload] Total time spent inside the function was 00:00:03.2483880

AssetId                              Name                      
-------                              ----                      
da35e4ad-f805-4bee-a971-d91dd0db8860 FLEX_TEST_AUTOMATED_UPLOAD
```

When I log in into LCS I can see that it has created the object in my asset library for the project, however it is in a failed state. Most likely because there is no .zip being uploaded. I presume I'm missing some libraries?

The machine I've used is a default D365FO development onebox.

**Comment by Splaxi** [comment]
Hi,

Could you verify D365FO version and .NET versions installed on the VM?

**Comment by oathgg** [comment]
Hi Motz,

The version of D365FO is PU35 and the .NET versions installed are 4.5.2, 4.6, 4.6.1, 4.7.2 and 4.8.
![image](https://user-images.githubusercontent.com/17101708/88629014-0631c280-d0af-11ea-8bb7-c1f69fb66423.png)
![image](https://user-images.githubusercontent.com/17101708/88629356-73455800-d0af-11ea-89ca-f5ad18f1009d.png)

**Comment by Splaxi** [comment]
Is it a LCS deployed, or an onebox?

**Comment by oathgg** [comment]
This is an onebox environment.

**Comment by Splaxi** [comment]
I'm going to download and deploy a local onebox with PU35, so I can see if I can reproduce the issue.

**Comment by Splaxi** [comment]
We just released a new version, could you please test with that and see if it makes any difference?

**Comment by oathgg** [comment]
@Splaxi 

Still the same result, did it work in your environment?

```powershell
PS C:\Users\Administrator> C:\Users\Administrator\Desktop\upload.ps1
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\PackageManagement.psd1'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\PackageManagement.format.ps1xml'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PowerShell.PackageManagement.dll'.
VERBOSE: Exporting cmdlet 'Find-Package'.
VERBOSE: Exporting cmdlet 'Get-Package'.
VERBOSE: Exporting cmdlet 'Get-PackageProvider'.
VERBOSE: Exporting cmdlet 'Get-PackageSource'.
VERBOSE: Exporting cmdlet 'Install-Package'.
VERBOSE: Exporting cmdlet 'Import-PackageProvider'.
VERBOSE: Exporting cmdlet 'Find-PackageProvider'.
VERBOSE: Exporting cmdlet 'Install-PackageProvider'.
VERBOSE: Exporting cmdlet 'Register-PackageSource'.
VERBOSE: Exporting cmdlet 'Save-Package'.
VERBOSE: Exporting cmdlet 'Set-PackageSource'.
VERBOSE: Exporting cmdlet 'Uninstall-Package'.
VERBOSE: Exporting cmdlet 'Unregister-PackageSource'.
VERBOSE: Importing cmdlet 'Find-Package'.
VERBOSE: Importing cmdlet 'Find-PackageProvider'.
VERBOSE: Importing cmdlet 'Get-Package'.
VERBOSE: Importing cmdlet 'Get-PackageProvider'.
VERBOSE: Importing cmdlet 'Get-PackageSource'.
VERBOSE: Importing cmdlet 'Import-PackageProvider'.
VERBOSE: Importing cmdlet 'Install-Package'.
VERBOSE: Importing cmdlet 'Install-PackageProvider'.
VERBOSE: Importing cmdlet 'Register-PackageSource'.
VERBOSE: Importing cmdlet 'Save-Package'.
VERBOSE: Importing cmdlet 'Set-PackageSource'.
VERBOSE: Importing cmdlet 'Uninstall-Package'.
VERBOSE: Importing cmdlet 'Unregister-PackageSource'.
VERBOSE: Exporting function 'Publish-Module'.
VERBOSE: Exporting function 'Find-Module'.
VERBOSE: Exporting function 'Save-Module'.
VERBOSE: Exporting function 'Install-Module'.
VERBOSE: Exporting function 'Update-Module'.
VERBOSE: Exporting function 'Uninstall-Module'.
VERBOSE: Exporting function 'Get-InstalledModule'.
VERBOSE: Exporting function 'Find-DscResource'.
VERBOSE: Exporting function 'Find-Command'.
VERBOSE: Exporting function 'Find-RoleCapability'.
VERBOSE: Exporting function 'Publish-Script'.
VERBOSE: Exporting function 'Find-Script'.
VERBOSE: Exporting function 'Save-Script'.
VERBOSE: Exporting function 'Install-Script'.
VERBOSE: Exporting function 'Update-Script'.
VERBOSE: Exporting function 'Uninstall-Script'.
VERBOSE: Exporting function 'Get-InstalledScript'.
VERBOSE: Exporting function 'Register-PSRepository'.
VERBOSE: Exporting function 'Set-PSRepository'.
VERBOSE: Exporting function 'Unregister-PSRepository'.
VERBOSE: Exporting function 'Get-PSRepository'.
VERBOSE: Exporting function 'Test-ScriptFileInfo'.
VERBOSE: Exporting function 'New-ScriptFileInfo'.
VERBOSE: Exporting function 'Update-ScriptFileInfo'.
VERBOSE: Exporting function 'Get-PackageProviderName'.
VERBOSE: Exporting function 'Get-Feature'.
VERBOSE: Exporting function 'Initialize-Provider'.
VERBOSE: Exporting function 'Get-DynamicOptions'.
VERBOSE: Exporting function 'Add-PackageSource'.
VERBOSE: Exporting function 'Resolve-PackageSource'.
VERBOSE: Exporting function 'Remove-PackageSource'.
VERBOSE: Exporting function 'Find-Package'.
VERBOSE: Exporting function 'Download-Package'.
VERBOSE: Exporting function 'Install-Package'.
VERBOSE: Exporting function 'Uninstall-Package'.
VERBOSE: Exporting function 'Get-InstalledPackage'.
VERBOSE: Exporting function 'Update-ModuleManifest'.
VERBOSE: Exporting alias 'fimo'.
VERBOSE: Exporting alias 'inmo'.
VERBOSE: Exporting alias 'upmo'.
VERBOSE: Exporting alias 'pumo'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='d365fo.tools'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'd365fo.tools'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://ultimatesoftwarebv.pkgs.visualstudio.com/_packaging/powershell/nuget/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Retry downloading 'https://ultimatesoftwarebv.pkgs.visualstudio.com/_packaging/powershell/nuget/v2' for '2' more times
VERBOSE: Retry downloading 'https://ultimatesoftwarebv.pkgs.visualstudio.com/_packaging/powershell/nuget/v2' for '1' more times
VERBOSE: Retry downloading 'https://ultimatesoftwarebv.pkgs.visualstudio.com/_packaging/powershell/nuget/v2' for '0' more times
WARNING: Cannot access 'https://ultimatesoftwarebv.pkgs.visualstudio.com/_packaging/powershell/nuget/v2'. Are you missing 'Credential' parameter in the cmdlet?
WARNING: Unable to resolve package source 'https://ultimatesoftwarebv.pkgs.visualstudio.com/_packaging/powershell/nuget/v2'.
VERBOSE: Total package yield:'0' for the specified package 'd365fo.tools'.
VERBOSE: The installation scope is specified to be 'AllUsers'.
VERBOSE: The specified module will be installed in 'C:\Program Files\WindowsPowerShell\Modules'.
VERBOSE: The specified Location is 'NuGet' and PackageManagementProvider is 'NuGet'.
VERBOSE: Downloading module 'd365fo.tools' with version '0.6.21' from the repository 'https://www.powershellgallery.com/api/v2'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='d365fo.tools'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PSFramework'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure.Storage'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='AzureRM.Profile'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='AzureAd'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PSNotification'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PSFramework'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PoshRSJob'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PSOAuthHelper'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PSFramework'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'' for ''.
VERBOSE: InstallPackage' - name='PSFramework', version='1.1.59',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: DownloadPackage' - name='PSFramework', version='1.1.59',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677\PSFramework\PSFramework.nupkg', uri='https://www.powershellgallery.com/api/v2/package/PSFramework/1.1.59'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/PSFramework/1.1.59'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/PSFramework/1.1.59'.
VERBOSE: Completed downloading 'PSFramework'.
VERBOSE: Hash for package 'PSFramework' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='PSFramework', version='1.1.59',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: InstallPackage' - name='AzureRM.profile', version='5.8.3',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: DownloadPackage' - name='AzureRM.profile', version='5.8.3',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677\AzureRM.profile\AzureRM.profile.nupkg', uri='https://www.powershellgallery.com/api/v2/package/AzureRM.profile/5.8.3'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/AzureRM.profile/5.8.3'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/AzureRM.profile/5.8.3'.
VERBOSE: Completed downloading 'AzureRM.profile'.
VERBOSE: Hash for package 'AzureRM.profile' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='AzureRM.profile', version='5.8.3',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: InstallPackage' - name='Azure.Storage', version='4.6.1',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: DownloadPackage' - name='Azure.Storage', version='4.6.1',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677\Azure.Storage\Azure.Storage.nupkg', uri='https://www.powershellgallery.com/api/v2/package/Azure.Storage/4.6.1'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/Azure.Storage/4.6.1'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/Azure.Storage/4.6.1'.
VERBOSE: Completed downloading 'Azure.Storage'.
VERBOSE: Hash for package 'Azure.Storage' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='Azure.Storage', version='4.6.1',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: Catalog file 'PSFramework.cat' is not found in the contents of the module 'PSFramework' being installed.
VERBOSE: For publisher validation, current module 'PSFramework' with version '1.1.59' with publisher name ''. Is this module signed by Microsoft: 'False'.
VERBOSE: For publisher validation, using the previously-installed module 'PSFramework' with version '1.1.59' under 'C:\Program Files\WindowsPowerShell\Modules\PSFramework\1.1.59' with publisher name ''. Is this module signed by Microsoft: 'False'.
VERBOSE: InstallPackage' - name='AzureAD', version='2.0.2.76',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: DownloadPackage' - name='AzureAD', version='2.0.2.76',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677\AzureAD\AzureAD.nupkg', uri='https://www.powershellgallery.com/api/v2/package/AzureAD/2.0.2.76'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/AzureAD/2.0.2.76'.
VERBOSE: Installing the dependency module 'PSFramework' with version '1.1.59' for the module 'd365fo.tools'.
WARNING: The version '1.1.59' of module 'PSFramework' is currently in use. Retry the operation after closing the applications.
VERBOSE: Module 'PSFramework' is in currently in use.
VERBOSE: Catalog file 'AzureRM.profile.cat' is not found in the contents of the module 'AzureRM.profile' being installed.
VERBOSE: For publisher validation, current module 'AzureRM.profile' with version '5.8.3' with publisher name ''. Is this module signed by Microsoft: 'False'.
VERBOSE: For publisher validation, using the previously-installed module 'AzureRM.profile' with version '5.8.3' under 'C:\Program Files\WindowsPowerShell\Modules\AzureRM.profile\5.8.3' with publisher name ''. Is this module signed by Microsoft: 'False'.
VERBOSE: Installing the dependency module 'AzureRM.profile' with version '5.8.3' for the module 'd365fo.tools'.
VERBOSE: Module 'AzureRM.profile' was installed successfully to path 'C:\Program Files\WindowsPowerShell\Modules\AzureRM.profile\5.8.3'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/AzureAD/2.0.2.76'.
VERBOSE: Completed downloading 'AzureAD'.
VERBOSE: Hash for package 'AzureAD' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='AzureAD', version='2.0.2.76',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: InstallPackage' - name='PoshRSJob', version='1.7.4.4',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: DownloadPackage' - name='PoshRSJob', version='1.7.4.4',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677\PoshRSJob\PoshRSJob.nupkg', uri='https://www.powershellgallery.com/api/v2/package/PoshRSJob/1.7.4.4'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/PoshRSJob/1.7.4.4'.
VERBOSE: Catalog file 'Azure.Storage.cat' is not found in the contents of the module 'Azure.Storage' being installed.
VERBOSE: For publisher validation, current module 'Azure.Storage' with version '4.6.1' with publisher name ''. Is this module signed by Microsoft: 'False'.
VERBOSE: For publisher validation, using the previously-installed module 'Azure.Storage' with version '4.6.1' under 'C:\Program Files\WindowsPowerShell\Modules\Azure.Storage\4.6.1' with publisher name ''. Is this module signed by Microsoft: 'False'.
VERBOSE: Installing the dependency module 'Azure.Storage' with version '4.6.1' for the module 'd365fo.tools'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/PoshRSJob/1.7.4.4'.
VERBOSE: Completed downloading 'PoshRSJob'.
VERBOSE: Hash for package 'PoshRSJob' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='PoshRSJob', version='1.7.4.4',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: Module 'Azure.Storage' was installed successfully to path 'C:\Program Files\WindowsPowerShell\Modules\Azure.Storage\4.6.1'.
VERBOSE: InstallPackage' - name='psnotification', version='0.5.3',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: DownloadPackage' - name='psnotification', version='0.5.3',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677\psnotification\psnotification.nupkg', uri='https://www.powershellgallery.com/api/v2/package/psnotification/0.5.3'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/psnotification/0.5.3'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/psnotification/0.5.3'.
VERBOSE: Completed downloading 'psnotification'.
VERBOSE: Hash for package 'psnotification' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='psnotification', version='0.5.3',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: InstallPackage' - name='PSOAuthHelper', version='0.2.6',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: DownloadPackage' - name='PSOAuthHelper', version='0.2.6',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677\PSOAuthHelper\PSOAuthHelper.nupkg', uri='https://www.powershellgallery.com/api/v2/package/PSOAuthHelper/0.2.6'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/PSOAuthHelper/0.2.6'.
VERBOSE: Catalog file 'AzureAD.cat' is not found in the contents of the module 'AzureAD' being installed.
VERBOSE: Valid authenticode signature found in the file 'AzureAD.psd1' for the module 'AzureAD'.
VERBOSE: For publisher validation, current module 'AzureAD' with version '2.0.2.76' with publisher name 'CN=Microsoft Root Certificate Authority 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US'. Is this module signed by Microsoft: 'True'.
VERBOSE: For publisher validation, using the previously-installed module 'AzureAD' with version '2.0.2.76' under 'C:\Program Files\WindowsPowerShell\Modules\AzureAD\2.0.2.76' with publisher name 'CN=Microsoft Root Certificate Authority 2011, O=Microsoft Corp
oration, L=Redmond, S=Washington, C=US'. Is this module signed by Microsoft: 'True'.
VERBOSE: Authenticode issuer 'CN=Microsoft Root Certificate Authority 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' of the new module 'AzureAD' with version '2.0.2.76' matches with the authenticode issuer 'CN=Microsoft Root Certificate Author
ity 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' of the previously-installed module 'AzureAD' with version '2.0.2.76'.
VERBOSE: Installing the dependency module 'AzureAD' with version '2.0.2.76' for the module 'd365fo.tools'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/PSOAuthHelper/0.2.6'.
VERBOSE: Completed downloading 'PSOAuthHelper'.
VERBOSE: Hash for package 'PSOAuthHelper' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='PSOAuthHelper', version='0.2.6',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: InstallPackage' - name='ImportExcel', version='7.1.1',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: DownloadPackage' - name='ImportExcel', version='7.1.1',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677\ImportExcel\ImportExcel.nupkg', uri='https://www.powershellgallery.com/api/v2/package/ImportExcel/7.1.1'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/ImportExcel/7.1.1'.
VERBOSE: Module 'AzureAD' was installed successfully to path 'C:\Program Files\WindowsPowerShell\Modules\AzureAD\2.0.2.76'.
VERBOSE: Catalog file 'PoshRSJob.cat' is not found in the contents of the module 'PoshRSJob' being installed.
VERBOSE: For publisher validation, current module 'PoshRSJob' with version '1.7.4.4' with publisher name ''. Is this module signed by Microsoft: 'False'.
VERBOSE: For publisher validation, using the previously-installed module 'PoshRSJob' with version '1.7.4.4' under 'C:\Program Files\WindowsPowerShell\Modules\PoshRSJob\1.7.4.4' with publisher name ''. Is this module signed by Microsoft: 'False'.
VERBOSE: Installing the dependency module 'PoshRSJob' with version '1.7.4.4' for the module 'd365fo.tools'.
VERBOSE: Module 'PoshRSJob' was installed successfully to path 'C:\Program Files\WindowsPowerShell\Modules\PoshRSJob\1.7.4.4'.
VERBOSE: Catalog file 'psnotification.cat' is not found in the contents of the module 'psnotification' being installed.
VERBOSE: For publisher validation, current module 'psnotification' with version '0.5.3' with publisher name ''. Is this module signed by Microsoft: 'False'.
VERBOSE: For publisher validation, using the previously-installed module 'psnotification' with version '0.5.3' under 'C:\Program Files\WindowsPowerShell\Modules\psnotification\0.5.3' with publisher name ''. Is this module signed by Microsoft: 'False'.
VERBOSE: Installing the dependency module 'psnotification' with version '0.5.3' for the module 'd365fo.tools'.
VERBOSE: Module 'psnotification' was installed successfully to path 'C:\Program Files\WindowsPowerShell\Modules\psnotification\0.5.3'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/ImportExcel/7.1.1'.
VERBOSE: Completed downloading 'ImportExcel'.
VERBOSE: Hash for package 'ImportExcel' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='ImportExcel', version='7.1.1',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: InstallPackage' - name='d365fo.tools', version='0.6.21',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: DownloadPackage' - name='d365fo.tools', version='0.6.21',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677\d365fo.tools\d365fo.tools.nupkg', uri='https://www.powershellgallery.com/api/v2/package/d365fo.tools/0.6.21'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/d365fo.tools/0.6.21'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/d365fo.tools/0.6.21'.
VERBOSE: Completed downloading 'd365fo.tools'.
VERBOSE: Hash for package 'd365fo.tools' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='d365fo.tools', version='0.6.21',destination='C:\Users\Administrator\AppData\Local\Temp\2\63597677'
VERBOSE: Catalog file 'PSOAuthHelper.cat' is not found in the contents of the module 'PSOAuthHelper' being installed.
VERBOSE: For publisher validation, current module 'PSOAuthHelper' with version '0.2.6' with publisher name ''. Is this module signed by Microsoft: 'False'.
VERBOSE: For publisher validation, using the previously-installed module 'PSOAuthHelper' with version '0.2.6' under 'C:\Program Files\WindowsPowerShell\Modules\PSOAuthHelper\0.2.6' with publisher name ''. Is this module signed by Microsoft: 'False'.
VERBOSE: Installing the dependency module 'PSOAuthHelper' with version '0.2.6' for the module 'd365fo.tools'.
VERBOSE: Module 'PSOAuthHelper' was installed successfully to path 'C:\Program Files\WindowsPowerShell\Modules\PSOAuthHelper\0.2.6'.
VERBOSE: Catalog file 'ImportExcel.cat' is not found in the contents of the module 'ImportExcel' being installed.
VERBOSE: For publisher validation, current module 'ImportExcel' with version '7.1.1' with publisher name ''. Is this module signed by Microsoft: 'False'.
VERBOSE: For publisher validation, using the previously-installed module 'ImportExcel' with version '7.1.1' under 'C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.1' with publisher name ''. Is this module signed by Microsoft: 'False'.
VERBOSE: Installing the dependency module 'ImportExcel' with version '7.1.1' for the module 'd365fo.tools'.
VERBOSE: Module 'ImportExcel' was installed successfully to path 'C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.1'.
VERBOSE: Catalog file 'd365fo.tools.cat' is not found in the contents of the module 'd365fo.tools' being installed.
VERBOSE: For publisher validation, current module 'd365fo.tools' with version '0.6.21' with publisher name ''. Is this module signed by Microsoft: 'False'.
VERBOSE: For publisher validation, using the previously-installed module 'd365fo.tools' with version '1.0.20823' under 'C:\Program Files\WindowsPowerShell\Modules\D365FO.Tools\1.0.20823' with publisher name ''. Is this module signed by Microsoft: 'False'.
VERBOSE: The externally managed, dependent module 'PSDiagnostics' is already installed on this computer.
VERBOSE: Module 'd365fo.tools' was installed successfully to path 'C:\Program Files\WindowsPowerShell\Modules\d365fo.tools\0.6.21'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PSFramework'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'PSFramework'.
VERBOSE: Skipping installed module PSFramework 1.0.12.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure.Storage'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'Azure.Storage'.
VERBOSE: Skipping installed module Azure.Storage 4.4.0.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='AzureAd'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'AzureAd'.
VERBOSE: Skipping installed module AzureAD 2.0.1.16.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PSNotification'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'PSNotification'.
VERBOSE: Skipping installed module psnotification 0.5.3.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PSOAuthHelper'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'PSOAuthHelper'.
VERBOSE: Skipping installed module PSOAuthHelper 0.2.3.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ImportExcel'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'ImportExcel'.
VERBOSE: Skipping installed module ImportExcel 7.1.0.
VERBOSE: [12:41:12][<Unknown>] Gathering all variables to assist the different cmdlets to function
VERBOSE: [12:41:13][Get-ApplicationEnvironment] Testing if we are running on a AOS server or not.
VERBOSE: [12:41:13][Get-ApplicationEnvironment] The machine is an AOS server.
VERBOSE: [12:41:13][Get-ApplicationEnvironment] Shadow cloning all relevant assemblies to the Microsoft.Dynamics.ApplicationPlatform.Environment.dll to avoid locking issues. This enables us to install updates while having d365fo.tools loaded
VERBOSE: [12:41:13][Test-PathExists] Testing the path: C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Authentication.Instrumentation.dll
VERBOSE: [12:41:13][Test-PathExists] Testing the path: C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Configuration.Base.dll
VERBOSE: [12:41:13][Test-PathExists] Testing the path: C:\AOSService\webroot\bin\Microsoft.Dynamics.BusinessPlatform.SharedTypes.dll
VERBOSE: [12:41:13][Test-PathExists] Testing the path: C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Framework.EncryptionEngine.dll
VERBOSE: [12:41:13][Test-PathExists] Testing the path: C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Security.Instrumentation.dll
VERBOSE: [12:41:13][Test-PathExists] Testing the path: C:\AOSService\webroot\bin\Microsoft.Dynamics.ApplicationPlatform.Environment.dll
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Cloning C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Authentication.Instrumentation.dll to C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Authentication.Instrumentation.dll_shadow.dll
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Loading C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Authentication.Instrumentation.dll_shadow.dll into memory
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Removing C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Authentication.Instrumentation.dll_shadow.dll
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Cloning C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Configuration.Base.dll to C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Configuration.Base.dll_shadow.dll
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Loading C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Configuration.Base.dll_shadow.dll into memory
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Removing C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Configuration.Base.dll_shadow.dll
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Cloning C:\AOSService\webroot\bin\Microsoft.Dynamics.BusinessPlatform.SharedTypes.dll to C:\AOSService\webroot\bin\Microsoft.Dynamics.BusinessPlatform.SharedTypes.dll_shadow.dll
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Loading C:\AOSService\webroot\bin\Microsoft.Dynamics.BusinessPlatform.SharedTypes.dll_shadow.dll into memory
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Removing C:\AOSService\webroot\bin\Microsoft.Dynamics.BusinessPlatform.SharedTypes.dll_shadow.dll
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Cloning C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Framework.EncryptionEngine.dll to C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Framework.EncryptionEngine.dll_shadow.dll
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Loading C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Framework.EncryptionEngine.dll_shadow.dll into memory
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Removing C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Framework.EncryptionEngine.dll_shadow.dll
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Cloning C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Security.Instrumentation.dll to C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Security.Instrumentation.dll_shadow.dll
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Loading C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Security.Instrumentation.dll_shadow.dll into memory
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Removing C:\AOSService\webroot\bin\Microsoft.Dynamics.AX.Security.Instrumentation.dll_shadow.dll
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Cloning C:\AOSService\webroot\bin\Microsoft.Dynamics.ApplicationPlatform.Environment.dll to C:\AOSService\webroot\bin\Microsoft.Dynamics.ApplicationPlatform.Environment.dll_shadow.dll
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Loading C:\AOSService\webroot\bin\Microsoft.Dynamics.ApplicationPlatform.Environment.dll_shadow.dll into memory
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Removing C:\AOSService\webroot\bin\Microsoft.Dynamics.ApplicationPlatform.Environment.dll_shadow.dll
VERBOSE: [12:41:13][Import-AssemblyFileIntoMemory] Total time spent inside the function was 00:00:00.0719972
VERBOSE: [12:41:13][Get-ApplicationEnvironment] All assemblies loaded. Getting environment details.
VERBOSE: [12:41:16][Get-D365LcsApiConfig] Extracting all the LCS configuration and building the result object.
VERBOSE: [12:41:16][Get-D365LcsApiConfig] Total time spent inside the function was 00:00:00.0180046
VERBOSE: [12:41:16][Update-LcsApiVariables] LcsApiActivetokenexpireson - 1596627430
VERBOSE: [12:41:16][Update-LcsApiVariables] LcsApiBearertoken - <HIDDEN_KEY>
VERBOSE: [12:41:16][Update-LcsApiVariables] LcsApiClientid - 
VERBOSE: [12:41:16][Update-LcsApiVariables] LcsApiLcsapiuri - https://lcsapi.lcs.dynamics.com
VERBOSE: [12:41:16][Update-LcsApiVariables] LcsApiProjectid - 
VERBOSE: [12:41:16][Update-LcsApiVariables] LcsApiRefreshtoken - <HIDDEN_KEY>
VERBOSE: [12:41:16][Variables.ps1] AADOAuthEndpoint - https://login.microsoftonline.com/common/oauth2/token
VERBOSE: [12:41:16][Variables.ps1] AccessToken - The variable was found - but the content masked while outputting.
VERBOSE: [12:41:16][Variables.ps1] AccountId - 
VERBOSE: [12:41:16][Variables.ps1] ActiveAzureStorageAccount - System.Collections.Hashtable
VERBOSE: [12:41:16][Variables.ps1] ActiveBroadcastMessageConfigName - 
VERBOSE: [12:41:16][Variables.ps1] ActiveEnvironment - System.Collections.Hashtable
VERBOSE: [12:41:16][Variables.ps1] ActiveLogicApp - System.Collections.Hashtable
VERBOSE: [12:41:16][Variables.ps1] AOSPath - C:\AOSService\webroot
VERBOSE: [12:41:16][Variables.ps1] args - 
VERBOSE: [12:41:16][Variables.ps1] AzcopyPath - C:\temp\d365fo.tools\AzCopy\AzCopy.exe
VERBOSE: [12:41:16][Variables.ps1] azure - System.Collections.Hashtable
VERBOSE: [12:41:16][Variables.ps1] BinDir - C:\AOSService\PackagesLocalDirectory
VERBOSE: [12:41:16][Variables.ps1] BinDirTools - C:\AOSService\PackagesLocalDirectory\bin
VERBOSE: [12:41:16][Variables.ps1] CanUseTrustedConnection - True
VERBOSE: [12:41:16][Variables.ps1] Company - DAT
VERBOSE: [12:41:16][Variables.ps1] Container - 
VERBOSE: [12:41:16][Variables.ps1] dataAccess - Microsoft.Dynamics.ApplicationPlatform.Environment.Settings.DataAccessConfig
VERBOSE: [12:41:16][Variables.ps1] DatabaseName - AxDB
VERBOSE: [12:41:16][Variables.ps1] DatabaseServer - localhost
VERBOSE: [12:41:16][Variables.ps1] DatabaseUserName - axdbadmin
VERBOSE: [12:41:16][Variables.ps1] DatabaseUserPassword - AOSWebSite@123
VERBOSE: [12:41:16][Variables.ps1] DefaultAOSName - usnconeboxax1aos
VERBOSE: [12:41:16][Variables.ps1] DefaultTempPath - c:\temp\d365fo.tools
VERBOSE: [12:41:16][Variables.ps1] doDotSource - False
VERBOSE: [12:41:16][Variables.ps1] environment - Microsoft.Dynamics.ApplicationPlatform.Environment.ApplicationEnvironment`1[Microsoft.Dynamics.ApplicationPlatform.Environment.WindowsAzureEnvironment]
VERBOSE: [12:41:16][Variables.ps1] EnvironmentType - LocalHostedTier1
VERBOSE: [12:41:16][Variables.ps1] Error - 
VERBOSE: [12:41:16][Variables.ps1] false - False
VERBOSE: [12:41:16][Variables.ps1] file - C:\Program Files\WindowsPowerShell\Modules\D365FO.Tools\1.0.20823\internal\tepp\send-d365message.tepp.ps1
VERBOSE: [12:41:16][Variables.ps1] foreach - 
VERBOSE: [12:41:16][Variables.ps1] function - update-d365user.ps1
VERBOSE: [12:41:16][Variables.ps1] Hosts - C:\Windows\System32\drivers\etc\hosts
VERBOSE: [12:41:16][Variables.ps1] IISHostFile - C:\Windows\System32\inetsrv\Config\applicationHost.config
VERBOSE: [12:41:16][Variables.ps1] importIndividualFiles - True
VERBOSE: [12:41:16][Variables.ps1] input - 
VERBOSE: [12:41:16][Variables.ps1] InstallationRecordsDir - C:\Logs\InstallationRecords
VERBOSE: [12:41:16][Variables.ps1] IsAdminRuntime - True
VERBOSE: [12:41:16][Variables.ps1] IsOnebox - True
VERBOSE: [12:41:16][Variables.ps1] item - PSFramework.Configuration.Config
VERBOSE: [12:41:16][Variables.ps1] LcsApiActivetokenexpireson - 1596627430
VERBOSE: [12:41:16][Variables.ps1] LcsApiBearertoken - <HIDDEN_KEY>
VERBOSE: [12:41:16][Variables.ps1] LcsApiClientid - 
VERBOSE: [12:41:16][Variables.ps1] LcsApiLcsapiuri - https://lcsapi.lcs.dynamics.com
VERBOSE: [12:41:16][Variables.ps1] LcsApiProjectid - 
VERBOSE: [12:41:16][Variables.ps1] LcsApiRefreshtoken - <HIDDEN_KEY>
VERBOSE: [12:41:16][Variables.ps1] logicApp - System.Collections.Hashtable
VERBOSE: [12:41:16][Variables.ps1] LogicAppEmail - 
VERBOSE: [12:41:16][Variables.ps1] LogicAppSubject - 
VERBOSE: [12:41:16][Variables.ps1] LogicAppUrl - 
VERBOSE: [12:41:16][Variables.ps1] maskOutput - AccessToken Token BearerToken Password RefreshToken
VERBOSE: [12:41:16][Variables.ps1] MaximumAliasCount - 4096
VERBOSE: [12:41:16][Variables.ps1] MaximumDriveCount - 4096
VERBOSE: [12:41:16][Variables.ps1] MaximumErrorCount - 256
VERBOSE: [12:41:16][Variables.ps1] MaximumFunctionCount - 4096
VERBOSE: [12:41:16][Variables.ps1] MaximumVariableCount - 4096
VERBOSE: [12:41:16][Variables.ps1] MetaDataDir - C:\AOSService\PackagesLocalDirectory
VERBOSE: [12:41:16][Variables.ps1] ModuleRoot - C:\Program Files\WindowsPowerShell\Modules\D365FO.Tools\1.0.20823
VERBOSE: [12:41:16][Variables.ps1] ModuleVersion - 0.6.15
VERBOSE: [12:41:16][Variables.ps1] MRConfigFile - C:\FinancialReporting\Server\ApplicationService\bin\MRServiceHost.settings.config
VERBOSE: [12:41:16][Variables.ps1] MyInvocation - System.Management.Automation.InvocationInfo
VERBOSE: [12:41:16][Variables.ps1] name - ActiveLogicApp
VERBOSE: [12:41:16][Variables.ps1] nameTemp - active.logic.app
VERBOSE: [12:41:16][Variables.ps1] null - 
VERBOSE: [12:41:16][Variables.ps1] PackageDirectory - C:\AOSService\PackagesLocalDirectory
VERBOSE: [12:41:16][Variables.ps1] Path - C:\Program Files\WindowsPowerShell\Modules\D365FO.Tools\1.0.20823\internal\scripts\variables.ps1
VERBOSE: [12:41:16][Variables.ps1] PSBoundParameters - System.Management.Automation.PSBoundParametersDictionary
VERBOSE: [12:41:16][Variables.ps1] PSCmdlet - System.Management.Automation.PSScriptCmdlet
VERBOSE: [12:41:16][Variables.ps1] PSCommandPath - C:\Program Files\WindowsPowerShell\Modules\D365FO.Tools\1.0.20823\D365FO.Tools.psm1
VERBOSE: [12:41:16][Variables.ps1] PSDefaultParameterValues - System.Management.Automation.DefaultParameterDictionary
VERBOSE: [12:41:16][Variables.ps1] PSScriptRoot - C:\Program Files\WindowsPowerShell\Modules\D365FO.Tools\1.0.20823
VERBOSE: [12:41:16][Variables.ps1] RegSplat - System.Collections.Hashtable
VERBOSE: [12:41:16][Variables.ps1] RegValue - C:\Logs\InstallationRecords
VERBOSE: [12:41:16][Variables.ps1] RoleVaule - Development
VERBOSE: [12:41:16][Variables.ps1] RsatPath - C:\Program Files (x86)\Regression Suite Automation Tool
VERBOSE: [12:41:16][Variables.ps1] RsatplaybackPath - C:\Users\Administrator\AppData\Roaming\regressionTool\playback
VERBOSE: [12:41:16][Variables.ps1] SAS - 
VERBOSE: [12:41:16][Variables.ps1] scriptBlock -  (Get-NetEventProvider -ShowInstalled | Where-Object name -like "Microsoft-Dynamics*" | Sort-Object Name).Name 
VERBOSE: [12:41:16][Variables.ps1] ServerRole - Development
VERBOSE: [12:41:16][Variables.ps1] serviceDrive - C:
VERBOSE: [12:41:16][Variables.ps1] SqlpackagePath - C:\Program Files (x86)\Microsoft SQL Server\140\DAC\bin\SqlPackage.exe
VERBOSE: [12:41:16][Variables.ps1] SQLTools - C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn
VERBOSE: [12:41:16][Variables.ps1] TfDir - C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\
VERBOSE: [12:41:16][Variables.ps1] TfsUri - 
VERBOSE: [12:41:16][Variables.ps1] TimeSignals - System.Collections.Hashtable
VERBOSE: [12:41:16][Variables.ps1] true - True
VERBOSE: [12:41:16][Variables.ps1] Url - https://usnconeboxax1aos.cloud.onebox.dynamics.com/
VERBOSE: [12:41:16][Variables.ps1] UserIsAdmin - True
VERBOSE: [12:41:16][Variables.ps1] WebConfig - web.config
VERBOSE: [12:41:16][Variables.ps1] WifServicesConfig - wif.services.config
VERBOSE: [12:41:16][<Unknown>] Finished outputting all the variable content.
VERBOSE: [12:41:16][Invoke-Authorization] Authenticating against Azure Active Directory (AAD).
VERBOSE: POST https://login.microsoftonline.com/common/oauth2/token with -1-byte payload
VERBOSE: received 3228-byte response of content type application/json; charset=utf-8
VERBOSE: [12:41:17][Set-D365LcsApiConfig] Working on LcsApiUri with https://lcsapi.lcs.dynamics.com
VERBOSE: [12:41:17][Set-D365LcsApiConfig] Setting d365fo.tools.lcs.lcsapiuri to https://lcsapi.lcs.dynamics.com
VERBOSE: [12:41:17][Register-PSFConfig] Registering d365fo.tools.lcs.lcsapiuri for UserDefault
VERBOSE: [12:41:17][Set-D365LcsApiConfig] Working on RefreshToken with <HIDDEN_KEY>
VERBOSE: [12:41:17][Set-D365LcsApiConfig] Setting d365fo.tools.lcs.refreshtoken to <HIDDEN_KEY>
VERBOSE: [12:41:17][Register-PSFConfig] Registering d365fo.tools.lcs.refreshtoken for UserDefault
VERBOSE: [12:41:17][Set-D365LcsApiConfig] Working on BearerToken with <HIDDEN_KEY>
VERBOSE: [12:41:17][Set-D365LcsApiConfig] Setting d365fo.tools.lcs.bearertoken to <HIDDEN_KEY>
VERBOSE: [12:41:17][Register-PSFConfig] Registering d365fo.tools.lcs.bearertoken for UserDefault
VERBOSE: [12:41:17][Set-D365LcsApiConfig] Working on ActiveTokenExpiresOn with 1596627677
VERBOSE: [12:41:17][Set-D365LcsApiConfig] Setting d365fo.tools.lcs.activetokenexpireson to 1596627677
VERBOSE: [12:41:17][Register-PSFConfig] Registering d365fo.tools.lcs.activetokenexpireson for UserDefault
VERBOSE: [12:41:17][Get-D365LcsApiConfig] Extracting all the LCS configuration and building the result object.
VERBOSE: [12:41:17][Get-D365LcsApiConfig] Total time spent inside the function was 00:00:00.0110034
VERBOSE: [12:41:17][Update-LcsApiVariables] LcsApiActivetokenexpireson - 1596627677
VERBOSE: [12:41:17][Update-LcsApiVariables] LcsApiBearertoken - <HIDDEN_KEY>
VERBOSE: [12:41:17][Update-LcsApiVariables] LcsApiClientid - 
VERBOSE: [12:41:17][Update-LcsApiVariables] LcsApiLcsapiuri - https://lcsapi.lcs.dynamics.com
VERBOSE: [12:41:17][Update-LcsApiVariables] LcsApiProjectid - 
VERBOSE: [12:41:17][Update-LcsApiVariables] LcsApiRefreshtoken - <HIDDEN_KEY>
VERBOSE: [12:41:17][Get-D365LcsApiToken] Total time spent inside the function was 00:00:00.9629392
VERBOSE: [12:41:17][Start-LcsUpload] Json payload for LCS generated.
VERBOSE: [12:41:17][New-JsonRequest] Building a HttpRequestMessage.
VERBOSE: [12:41:17][New-JsonRequest] Adding content to the HttpRequestMessage.
VERBOSE: [12:41:17][New-JsonRequest] Adding Authorization token to the HttpRequestMessage.
VERBOSE: [12:41:17][Start-LcsUpload] Invoke LCS request.
VERBOSE: [12:41:17][Get-AsyncResult] Building the Task Waiter and start waiting.
VERBOSE: [12:41:20][Start-LcsUpload] Extracting the response received from LCS.
VERBOSE: [12:41:20][Get-AsyncResult] Building the Task Waiter and start waiting.
VERBOSE: [12:41:20][Start-LcsUpload] Extracting the response received from LCS.
VERBOSE: [12:41:20][Start-LcsUpload] Extracting the asset json response received from LCS.
VERBOSE: [12:41:20][Start-LcsUpload] Total time spent inside the function was 00:00:02.6933681
VERBOSE: [12:41:20][Invoke-D365LcsUpload] Start response
VERBOSE: [12:41:20][Copy-FileToLcsBlob] Initializing the needed .net objects to work against Azure Blob.
New-Object : Cannot find type [Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob]: verify that the assembly containing this type is loaded.
At line:42 char:18
+ ... cloudblob = New-Object -TypeName Microsoft.WindowsAzure.Storage.Blob. ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
 
[12:41:20][Copy-FileToLcsBlob] Something went wrong while uploading the desired file to Azure Blob. | You cannot call a method on a null-valued expression.
WARNING: [12:41:20][Copy-FileToLcsBlob] Stopping because of errors
VERBOSE: [12:41:20][Invoke-D365LcsUpload] Upload response
VERBOSE: [12:41:20][New-JsonRequest] Building a HttpRequestMessage.
VERBOSE: [12:41:20][New-JsonRequest] Adding Authorization token to the HttpRequestMessage.
VERBOSE: [12:41:20][Complete-LcsUpload] Sending the commit request against LCS
VERBOSE: [12:41:20][Get-AsyncResult] Building the Task Waiter and start waiting.
VERBOSE: [12:41:21][Complete-LcsUpload] Parsing the commitResult for success
VERBOSE: [12:41:21][Complete-LcsUpload] Total time spent inside the function was 00:00:01.2006643
VERBOSE: [12:41:21][Invoke-D365LcsUpload] Commit response
VERBOSE: [12:41:21][Invoke-D365LcsUpload] Total time spent inside the function was 00:00:04.1680862

AssetId                              Name                          
-------                              ----                          
e6f15ca2-52d8-43af-9f13-f61f776f8b9b FLEX_TEST_AUTOMATED_UPLOAD.zip```

**Comment by Splaxi** [comment]
My update to PU35 gave me some issues, but they should be handled now. Updating to PU35 as we speak.

I can see that the box is borned with 4.5 and 4.6.1 in .NET versions.

Will run my first test without Windows Update (if possible) and the do a complete Windows Update and test again.

**Comment by Splaxi** [comment]
So - I did some testing.

The downloaded VHD was a PU32, from the Shared Asset Library on LCS. I updated the machine to PU35, with some issues along the way with retail stuff, that we don't need.

The machine only has .NET 4.5 and .NET 4.6.1 installed.

I didn't do anything special, before uploading and it works.

Will run Windows Update and make sure I have everything installed and updated. Then I'll test again. After that I'll install 4.7.2, and do some more testing, and finally 4.8 and do the last testing.

**Comment by oathgg** [comment]
Hi @Splaxi 

Our build and release agents are running 4.7.0.
![image](https://user-images.githubusercontent.com/17101708/89874029-9138af80-dbbb-11ea-9f4e-72eb774f1d35.png)

**Comment by Splaxi** [comment]
Okay.

Bad news, for you. I'm able to upload using the Invoke-d365lcsupload cmdlet, regardless of which .Net Framework versions I have installed.

![image](https://user-images.githubusercontent.com/8750181/90073903-5db06f00-dcfa-11ea-89d8-ad5a2f1f15df.png)

I'm certain that we are overlooking something.

Could you share you script from the upload.ps1 file that you shared the output from?

My code is:
```powershell
Get-D365LcsApiToken -ClientId ... | Set-D365LcsApiConfig ....
Invoke-D365LcsUpload ....
```

If you want, we can do some screen sharing, or take this "offline" - so we can share private details, to get you going with you things...

**Comment by oathgg** [comment]
Hi @Splaxi 

The entire script is:
```powershell
$VerbosePreference = "Continue"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls, [Net.SecurityProtocolType]::Tls11, [Net.SecurityProtocolType]::Tls12
Install-Module -Name d365fo.tools -Force

Get-D365LcsApiToken `
-ClientId "xxxxxx" `
-Username "xxxxxxx" `
-Password "xxxxx" `
-LcsApiUri "https://lcsapi.lcs.dynamics.com" `
| Set-D365LcsApiConfig

Invoke-D365LcsUpload `
-ProjectId xxxx `
-FilePath "C:\Temp\AXDeployableRuntime_2020.7.8.1.zip" `
-FileType "Software Deployable Package" `
-FileName "FLEX_TEST_AUTOMATED_UPLOAD.zip" `
-LcsApiUri "https://lcsapi.lcs.dynamics.com"
```

Let's do some screen sharing when you have time, it feels like as if I'm missing a DLL.

**Comment by Splaxi** [comment]
And you are running it from a VHD / VM that you downloaded from LCS Shared Asset library and updated it to PU35?

If you have twitter, please ping me @splaxi - then we can plan how to continue from here.

**Comment by Splaxi** [comment]
What timezone are you in? Just to make sure we can align our schedule...

**Comment by Splaxi** [comment]
@oathgg 

I never heard back from you. Are you still stuck with this?
